### PR TITLE
add handling for custom icons

### PR DESCRIPTION
**Pull request by bdantas**
mktrayicon is beautiful: It does one thing, extremely well. Very, very nice.

In its current form, mktrayicon only handles stock icons. I added the ability to handle custom icons (given as a path) as well.

Cheers,
Bruno "GNUser" Dantas

### CODE REVIEW

**Comment by jonhoo** [comment]
Thanks, this looks great! Could you please also update the README to mention that arguments to `i` with a `/` are treated as a path?

**Comment by bdantas** [comment]
I agree. What you suggested is much better. Here you go!

**Comment by bdantas** [comment]
Sure. README is now updated.

**Comment by jonhoo** [comment]
Excellent, thank you!

**Pull request merged**
