### PR TITLE
Handle newlines in params

### PR DESCRIPTION
**Pull request by jonhoo**

### CODE REVIEW

**Comment by jonhoo** [comment]
@bdantas Could you give this version a try and see if it behaves like you would expect on the FIFO?

**Comment by bdantas** [comment]
No, only first line shows up:

bruno@thinkpad:~/Desktop409$ mkfifo /tmp/pipe
bruno@thinkpad:~/Desktop410$ ./mktrayicon -t "hello
> world" -i dialog-ok /tmp/pipe &
[1] 4869
# at this point, tooltip shows "hello world"
bruno@thinkpad:~/Desktop414$ echo "t goodbye
> world" >/tmp/pipe
reading
read
cmd t
Setting tooltip to 'goodbye'
reading
read
cmd w
Unknown command: 'w'
reading
read
closed
bruno@thinkpad:~/Desktop416$ 
# at this point, tooltip shows "goodbye"

**Comment by jonhoo** [comment]
For your first example, that command works correctly to me. That is, if I run:
```
$ mkfifo /tmp/pipe
$ ./mktrayicon -t "hello
world" -i dialog-ok /tmp/pipe &
```
And then hover over the icon, the tooltip shows:
```
hello
world
```
Is that not the case for you?

As for the FIFO, you need to quote the string. So:
```
$ echo "t 'goodbye
world'" >/tmp/pipe
```
Does that work?

**Comment by bdantas** [comment]
> For your first example, that command works correctly to me. That is, if I run:
> 
> ```
> $ mkfifo /tmp/pipe
> $ ./mktrayicon -t "hello
> world" -i dialog-ok /tmp/pipe &
> ```
> 
> And then hover over the icon, the tooltip shows:
> 
> ```
> hello
> world
> ```
> 
> Is that not the case for you?

That works for me, too.

> As for the FIFO, you need to quote the string. So:
> 
> ```
> $ echo "t 'goodbye
> world'" >/tmp/pipe
> ```
> 
> Does that work?

Yes, single quotes within double quotes works when writing to the pipe. However, I was surprised that double quotes within single quotes doesn't work:
```
$ echo 't "goodbye
> world"' >/tmp/pipe
Setting tooltip to '"goodbye'
Unknown command: 'w'
```

**Comment by jonhoo** [comment]
Yeah, I implemented only one type of quoting :) I guess I could implement `"` as well if you think it's necessary?

The double quoting (`"'...'"`) is just because of your shell — `mktrayicon` just sees the stuff inside the outermost quotes, which are removed by your shell before fork/exec.

**Comment by bdantas** [comment]
> Yeah, I implemented only one type of quoting :) I guess I could implement `"` as well if you think it's necessary?

I would implement both, lest the user be surprised (as I was) if he picks the wrong kind. Gosh, this seems much more complicated than my proposed solution to this issue using escape codes. I hope you're right about this fix being superior despite the added overhead :)

> The double quoting (`"'...'"`) is just because of your shell — `mktrayicon` just sees the stuff inside the outermost quotes, which are removed by your shell before fork/exec.

Got it. That makes perfect sense.

**Comment by jonhoo** [comment]
> I would implement both, lest the user be surprised (as I was) if he picks the wrong kind.

That's a good point! Fixed :)

> Gosh, this seems much more complicated than my proposed solution to this issue using escape codes. I hope you're right about this fix being superior despite the added overhead :)

It's not that much more complicated really — I fixed some other issues with line parsing too while I was at it (like trailing whitespace not being trimmed correctly). With this version people can safely write any string into quotes, and not have to check whether it contains escape sequences that will be rendered weirdly or newlines they need to transform. It will "just work" (at least that's the idea). It also enables us, down the line, to add stuff like variables and the like inside quoted strings should we want it.

The big reason why the code is as verbose as it is is that C doesn't really have an off-the-shelf quoted string parsed that fits this (at least as far as I could find). It's a shame really, but such is life. The current implementation definitely has some weird quirks, but should generally work as expected.

**Comment by bdantas** [comment]
Nice. I can confirm that the pipe can handle newlines within both types of quotes now.

Did you intend to leave `#define DEBUG 1` at the top? Also, in the `main` function we've been using the variable `pipe`, so `FILE *fifo;` is superfluous. BTW `pipe` is a pointer to char, not a pointer to FILE. Maybe that a rookie mistake from prior merge but it works. Do you want to leave it like that?

**Comment by jonhoo** [comment]
Fixed all of those now! Anything else you spot that we should fix before merging?

**Comment by bdantas** [comment]
I can't find anything else. Looks good and works perfectly as far as I can tell :)

**Comment by bdantas** [comment]
Just one small thing. This does not work at all (result in "none" icon without any tooltip):

```
mktrayicon $pipe &
printf "i dialog-error" >$pipe
printf "t 'hello\nworld'" >$pipe
```

But this works fine:
```
mktrayicon $pipe &
printf "i dialog-error\n" >$pipe
printf "t 'hello\nworld'" >$pipe
```

Is there a reason why the first `printf` needs a trailing newline, or is this a bug?

**Comment by bdantas** [comment]
I looked at `watch_fifo` again. It seems that the function needs either a newline (if there are no quotes) or a closing quote (if there is an opening quote) to know where to stop reading. 

So it seems that what I observed in my previous post is not a bug. I'd add a statement somewhere in the README that says a newline is necessary if there are no quotes in what is written to the pipe.

**Comment by bdantas** [comment]
Oops, README already says "Each command should be terminated by a newline" (head beats against wall).

**Comment by jonhoo** [comment]
Merged!

**Comment by bdantas** [comment]
Great!

BTW, I migrated all my system tray applets from `yad` to my `\n`-parsing fork of `mktrayicon`, now again to official version of `mktrayicon` (my fork is dead). I really admire `mktrayicon`'s simple elegance. Thank you for creating it and making it free software.

I'm glad I could pitch in a little. Thanks for your patience--I'm strong in some areas, but C is not one of them. I know just enough to get in trouble, but I'm looking to change that :)

Happy hacking!

**Comment by jonhoo** [comment]
Glad to hear it worked out! And that you are finding `mktrayicon` useful :D

Always happy to have help, even if it takes a bit of mentoring. I think if I re-visited the project again today, I would re-write it in something else (probably Rust), because C is a bit of a pain to work with, but it _does_ mean the project stays small and simple!

**Pull request merged**
